import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Useful",
    lastName: "Balika",
    bio: "Dilo ko choo jane wali balika",
    avatar: "https://i.pravatar.cc/300",
    username: "adarshbalika",
    password: "adarshBalika123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Khushal",
    lastName: "Sharma",
    bio: "Software Maker",
    avatar: "https://i.pravatar.cc/300",
    username: "logan1x",
    password: "meNhiBataunga",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Vishal",
    lastName: "Sharma",
    bio: "Sports, love and life",
    avatar: "https://i.pravatar.cc/300",
    username: "adbhutchawda",
    password: "adbhut123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Test",
    lastName: "man",
    bio: "Loves to read & sing.",
    avatar: "https://i.pravatar.cc/300",
    username: "testcool",
    password: "test123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ashwini",
    lastName: "Pandya",
    bio: "Mandala artist | Teen",
    avatar: "https://i.pravatar.cc/300",
    username: "ashp",
    password: "ash123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Sachin",
    lastName: "Sharma",
    bio: "Another GitHub user",
    avatar: "https://i.pravatar.cc/300",
    username: "logan1x34",
    password: "khush123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Pratham",
    lastName: "Agrawal",
    bio: "That's my business & none of yours.",
    avatar: "https://i.pravatar.cc/300",
    username: "prathamagrawal8",
    password: "pratham123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Notso",
    lastName: "khilji",
    bio: "Reading Harry potter",
    avatar: "https://i.pravatar.cc/300",
    username: "alauddin_khilji",
    password: "alak123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ajit",
    lastName: "Singh",
    bio: "Student",
    avatar: "https://i.pravatar.cc/300",
    username: "khiladi786",
    password: "khiladi123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
